server:
    port: 8001

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/manual_contest?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root@MySQL!!!
        driver-class-name: com.mysql.cj.jdbc.Driver

    jackson:
        time-zone: GMT+8

mybatis-plus:
    configuration:
        cache-enabled: true
    mapper-locations: classpath:cn/edu/seu/manualcontest/mapper/*.xml
    type-aliases-package: cn.edu.seu.manualcontest

app:
    jwtExpirationInMs: 604800000
    jwtSecret: Secret

