export default {
  ROLE_STUDENT: "ROLE_STUDENT",
  ROLE_ADMIN: "ROLE_ADMIN",

  STATUS_NOT_START: "STATUS_NOT_START",
  STATUS_GENERATED: "STATUS_GENERATED",
  STATUS_STARTED: "STATUS_STARTED",
  STATUS_SUBMITTED: "STATUS_SUBMITTED",
  STATUS_NOT_SUBMITTED: "STATUS_NOT_SUBMITTED",

  AUTH_ALL: "AUTH_ALL",
  AUTH_PART: "AUTH_PART",

  TIME_LIMIT: 30 * 60 * 1000,
  CHOICE_QUESTION_NUM: 30,
  JUDGE_QUESTION_NUM: 0,
  CHOICE_QUESTION_SCORE: 1,
  JUDGE_QUESTION_SCORE: 1
};
